spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shedlock_DB?useSSL=false&serverTimezone=Europe/Rome
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  batch:
    job:
     enabled: false
    initialize-schema: always
